controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "mid_left_wheel_joint", "back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "mid_right_wheel_joint", "back_right_wheel_joint"]
    cmd_vel_timeout: 0.9 # Saniyeler içinde, komut gelmezse robot durur
    wheel_separation: 0.7 # Robotunuzun tekerlekleri arasındaki mesafe (metre)
    wheel_radius: 0.1 # Tekerlek yarıçapı (metre)

    publish_limited_velocity: true
    publish_wheel_tf: true
    publish_odom_tf: true
    publish_rate: 50.0

    # Enkoderlerin ters yöne dönmesi durumunda true/false
    left_encoder_pulses_per_revolution: 1.0 # Eğer enkoder kullanıyorsanız
    right_encoder_pulses_per_revolution: 1.0

    # Hareket limitleri (isteğe bağlı)
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 2.0
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 5.0
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 2.5
