slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    # DENGELİ KALİTE AYARLARI
    debug_logging: false
    throttle_scans: 2                    # Daha az throttle (5 -> 2)
    transform_publish_period: 0.04       # 25Hz TF (daha hızlı)
    map_update_interval: 2.0             # Daha hızlı harita güncellemesi (5.0s -> 2.0s)
    resolution: 0.05                     # Daha yüksek çözünürlük (0.1 -> 0.05)
    max_laser_range: 20.0                # Daha uzun menzil (12.0m -> 20.0m)
    min_laser_range: 0.25                # Lidar'ın minimum menziline uygun ayar
    minimum_time_interval: 0.2           # Daha hızlı işlem
    transform_timeout: 1.0
    tf_buffer_duration: 30.0
    stack_size_to_use: 60000000
    enable_interactive_mode: false       # RViz GLSL hatasını ayıklamak için kapatıldı
    map_start_at_dock: true
    publish_occupancy_grid: true

    # BUFFER AYARLARI
    scan_buffer_size: 70
    scan_queue_size: 15
    scan_buffer_maximum_scan_distance: 20.0
    
    # DENGELİ HAREKET AYARLARI
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    
    # GÜVENİLİR ODOMETRİ İÇİN SCAN MATCHING AYARLARI
    link_match_minimum_response_fine: 0.15   # Eşleşme için daha yüksek güven eşiği
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 2.0
    loop_match_minimum_response_coarse: 0.5   # Daha agresif loop closure
    loop_match_minimum_response_fine: 0.6     # Daha agresif loop closure

    # CORRELATION PARAMETRELERİ
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # LOOP CLOSURE PARAMETRELERİ
    loop_search_space_dimension: 6.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # GÜVENİLİR ODOMETRİ İÇİN SCAN MATCHER (Daha Dengeli)
    distance_variance_penalty: 0.9          # Odometriye güven, ancak lazere de izin ver (0.8 -> 0.9)
    angle_variance_penalty: 1.2             # Odometriye daha fazla güven
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5           # Lazerin düzeltme yapmasına daha fazla izin ver (0.9 -> 0.5)
    use_response_expansion: true