slam_toolbox:
  ros__parameters:
    
    # BASIC ROS PARAMETERS
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    
    # ESSENTIAL MESSAGE FILTERING (conservative values)
    debug_logging: false
    throttle_scans: 3                    # Process every 3rd scan (instead of 10)
    transform_publish_period: 0.05       # Standard rate
    map_update_interval: 5.0             # Slower map updates
    resolution: 0.05                     # Standard resolution
    max_laser_range: 30.0                # Full range
    minimum_time_interval: 0.5           # Slower movement required
    transform_timeout: 0.5               # Shorter timeout
    tf_buffer_duration: 30.0             # Standard buffer
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    
    # BUFFER SETTINGS (moderate)
    scan_buffer_size: 10                 # Small buffer for testing
    scan_buffer_maximum_scan_distance: 30.0
    
    # MOVEMENT REQUIREMENTS (relaxed)
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2        # Standard movement
    minimum_travel_heading: 0.2         # Standard rotation
    
    # SCAN MATCHING (defaults)
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 10.0
    loop_search_maximum_distance: 4.0
    do_loop_closing: true                # ENABLED but conservative
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    
    # CORRELATION (defaults)
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    
    # LOOP CLOSURE (defaults)
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    
    # SCAN MATCHER (defaults)
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true 