slam_toolbox:
  ros__parameters:
    
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    
    # TRANSFORM TIMING FIX - Critical for Gazebo
    debug_logging: false
    transform_timeout: 1.0        # 1 second timeout (was 0.05)
    tf_buffer_duration: 15.0      # 15 second TF buffer (was 10.0)
    scan_buffer_size: 50          # Smaller buffer to reduce memory
    scan_buffer_maximum_scan_distance: 25.0
    minimum_time_interval: 1.0     # Process every 1 second (was 0.5)
    
    # SCAN PROCESSING - Reduced frequency
    throttle_scans: 1             # Process every scan (was 10)
    minimum_travel_distance: 0.3   # Move 30cm before updating (was 0.1)
    minimum_travel_heading: 0.26   # 15 degrees rotation (was 0.17)
    
    # MAP SETTINGS
    resolution: 0.05              # 5cm resolution
    map_update_interval: 2.0      # Update map every 2 seconds
    map_start_at_dock: true
    
    # CORRELATIVE SCAN MATCHING - Less aggressive
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.03
    
    # LOOP CLOSURE - Simpler settings
    loop_search_maximum_distance: 8.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 15
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    
    # SCAN MATCHER - Stable settings
    distance_variance_penalty: 0.3
    angle_variance_penalty: 0.1778
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true 